channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=21.2.4
- pip:
  - mlflow
  - cloudpickle==2.2.0
  - scikit-learn==1.1.1
  - typing-extensions==4.3.0
  - matplotlib
  - seaborn
name: mltech
